### ISSUE TITLE
Setup Basic Layout

### ISSUE THREAD

**Issue by hellodebs** [hellodebs/sop#4]
# Value Statement

As a user
I want to see the structured restaurant page starting with the menu right away (as home)
so that I can directly start choosing food/drinks.

# Description
Structure UI with header, main, footer (without main section content).

# Acceptance criteria

- It should be responsive, working for different screen sizes
- The user should be directed to the Menu page.
- The header should display the title according to the page that's currently selected.

# Complexity
medium

# Tasks
- [x] Create markup page
- [x] install `react-router-dom`
- [x] Define route `/menu`, `/order`,`/bill`,</service>

- [x] Create CSS Layout
- [x] Create Components and import:
    - [x] MenuPage
- [x] Make header change according to current active page
