### ISSUE TITLE
Setup Order Page

### ISSUE THREAD

**Issue by hellodebs** [hellodebs/sop#6]
# Value Statement

As a developer
I want to create an order page
so that the user has a clean overview later.

# Description

Create component and link to icon in footer.

# Acceptance criteria

- The user should be able to navigate from the Menu Page to Order Page.

# Complexity
medium

# Tasks
- [x] Also modify MenuPage Component
- [x] Create OrderPage Component
- [x] Make header change according to current active page.
