### ISSUE TITLE
Setup Service Page

### ISSUE THREAD

**Issue by hellodebs** [hellodebs/sop#7]
# Value Statement

As a developer
I want to create an extra service section
so that the client can use this function just in case.

# Description

Create component and link to icon in footer.

# Acceptance criteria

- The user should be able to navigate between menu, order, bill and service page.

# Complexity
medium

# Tasks
- [x] Create markup page
- [x] Create Service Page Component
- [x] Make header change according to current active page.
