### ISSUE TITLE
Setup Bill Page

### ISSUE THREAD

**Issue by hellodebs** [hellodebs/sop#8]
# Value Statement

As a developer
I want to create a bill page
so that the user can look into his interim bill.

# Description

Create component and link to icon in footer.

# Acceptance criteria

- The user should be able to navigate between, menu, order and bill.

# Complexity
medium

# Tasks
- [x] Create markup page
- [x] Create BillPage Component
- [x] Make header change according to current active page.
