### ISSUE TITLE
Mock Json file

### ISSUE THREAD

**Issue by hellodebs** [hellodebs/sop#9]
# Value Statement

As a developer
I want to create a mock json file
so that I can develop the frontend without a real backend

# Description

Create objects in a json file to run through to fake the backend.

# Acceptance criteria

- I have various content to choose from.
- The user should be able to see the content and scroll through it in the menu page.

# Complexity
large

# Tasks
- [x] Create json file
- [x] Create various food content in text
- [x] Add URLs for thumbnail pics of food.
